### ISSUE TITLE
[Feature] better daterange selection in forecast pipelines

### ISSUE THREAD

**Issue by FrankKr** [OpenSTEF/openstef#121]
**Is your feature request related to a problem? Please describe.**
The forecast pipelines (forecast and basecase) determine a 'relevant' timeframe for forecasts within the pipeline. 
In practice, this means a forecast_pipeline can only return forecasts for moments in the future. If we want to make a backtest, the forecast_pipeline can therefore not be used.

**Describe the solution you'd like**
Desired to be able to use the forecast_pipeline independent of 'now', so it can also be used more generically, for example in backtests. Either make use of an optional input argument for the forecast_pipeline function, or move the selection of daterange to some other part of the code.

**Describe alternatives you've considered**
- Quick: The forecast_pipeline could determine relevant moments automatically based on for which input de 'load' (or in general, the target variable) is nan. 
- Nicer: You can use an optional input argument which gives the daterange-selection-strategy, using the 'Strategy design pattern'. This is a function which gets the complete input_dataframe as input and returns the relevant selection. E.g. only moments in the future, all only moments with load==nan, or some other criteria

**Additional context**
Relevant for *all* forecast pipelines. E.g. 'regular', 'components', 'basecase'.

**Comment by Davidswinkels** [comment]
The quick alternative solution has been implemented. If we want other solutions, we can make new issue.
