### ISSUE TITLE
[Feature] Implement sigmoid model

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [OpenSTEF/openstef#185]
WHAT: Implement the RTE sigmoid model.

HOW:
- Use RTE sigmoid model and wrap it like the xgb model
- unit tests

TEST:
- The RTE sigmoid model is available for training and predicting

**Comment by Davidswinkels** [comment]
The CustomModel feature makes this feature possible and this issue possibly can be closed. 

@FrankKr @JanMaartenvanDoorn would it be interesting to have a base sigmoid model in openSTEF?

**Comment by Davidswinkels** [comment]
@AlexisMignon @BenoitHardier explain why sigmoid models are better in some contexts than xgb models. Then it's easier for Frank/JM to understand the benefits

**Comment by JonitaRuiter** [comment]
Sigmoid model is implemented to forecast wind power output in the calculate_windturbine_power_output function (https://github.com/OpenSTEF/openstef/blob/main/openstef/feature_engineering/weather_features.py#L276).
