### ISSUE TITLE
Dashboard documentation

### ISSUE THREAD

**Issue by Sander3003** [OpenSTEF/openstef#241]
As a (potentail) user
I would like to see an explenation of the openSTEF dashboard and the different subsections
So I get a better understanding what is shown and why it is shown and will help (new) user to understand is faster.

**Comment by charlottecvn** [comment]
@Sander3003 the openstef dashboard documentation can be found [here](https://raw.githack.com/OpenSTEF/.github/main/profile/html/openstef_dashboard_doc.html), this can be accessed through the readme of the [organization OpenSTEF page](https://github.com/OpenSTEF).
