### ISSUE TITLE
[Documentation] Add small demo notebook which demonstrates basis openstf functionality

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [OpenSTEF/openstef#245]
WHAT: To show how openSTEF works we would like to have a small notebook with documentation.

HOW:
- Make a jupyter notebook with a minimal openSTEF example
- Look if we can host this somewhere where people can play with it interactively (Googlecolab)
- make several examples for specific subjects
- Add check that the notebooks works in the CI/CD
- Look into jupytext

TEST:
- demo notebook online
- CI/CD check online
- link to notebook in the readme file

**Comment by FrankKr** [comment]
@JanMaartenvanDoorn Is this not already covered by the repo: https://github.com/OpenSTEF/openstef-offline-example
With the interactive environment: https://mybinder.org/v2/gh/alliander-opensource/openstf-offline-example/master?

Perhaps including those links in the readme already satisfies this issue?

**Comment by FrankKr** [comment]
Fixed by openstef-offline-example
