### ISSUE TITLE
[Feature] modelhandler and modelwrapper of proloaf are integrated in openstef

### ISSUE THREAD

**Issue by charlottecvn** [OpenSTEF/openstef#286]
WHAT: The current proloaf regressor makes use of an modelhandler and modelwrapper. Update the proloaf regressor to use both the handler and the wrapper

HOW:
- change imports for the modelhandler and modelwrapper in the proloaf regressor

TEST:
- PR approved

**Comment by Davidswinkels** [comment]
Possibly branch (feature-issue-286-modelhandler_proloaf) has a first implementation to setup a modelhandler for proloaf. When we start working on this issue we can reuse the branch, or start from scratch if that's easier later due to a lot of changes.
