### ISSUE TITLE
Type annotation incompatible with Python 3.8 in Feature Adder code

### ISSUE THREAD

**Issue by AlexisMignon** [OpenSTEF/openstef#310]
The following line directly uses the `list` type for the type annotation which is possible only with >= 3.9.

https://github.com/OpenSTEF/openstef/blob/35a0c46fb6c6a97c3761b8f7c518dbf299637d5c/openstef/feature_engineering/feature_adder.py#L33

Should simply replace `list` with `List`.

**Comment by Davidswinkels** [comment]
Hey Alexis. Thanks for the suggestion! The linked PR should resolve the issue. Can you review if PR solves the issue? Thanks!
