### ISSUE TITLE
Feature importances can be None but the reporter try to write it on disk

### ISSUE THREAD

**Issue by BenoitHardier** [OpenSTEF/openstef#348]
WHAT:
Reporter writes plots on disk. Specifically, the importance feature plot is writting as `weight_plot.html` but the plot can be None. In this case, it raises an error.

HOW:
Checks if `report.feature_importance_figure` is None and skips the writting according the result.

TEST:
Check both with and without feature_importance the report saving.

**Comment by Davidswinkels** [comment]
Heyo. Again good catch. Will fix this

**Comment by Davidswinkels** [comment]
Made fix: https://github.com/OpenSTEF/openstef/pull/349
