### ISSUE TITLE
Add some specific metrics for quantiles model

### ISSUE THREAD

**Issue by BenoitHardier** [OpenSTEF/openstef#404]
**WHAT:**
To have more insights about quantiles model we propose to report some specific metrics in addition to common regression metrics like RMSE, MAE, R2. 

**HOW:**  
We propose to compute the *fiability* on each quantile in the quantiles list of the pj.  
The *fiability* for a quantile is the proportion of the set where the actual ground truth is less than the quantile.  
$fiability_{q}= \frac{1}{|valset|} \sum_{y_{true} \in valset} \mathbb{1}(y_{true} \leq q)$  

If the model is well calibrated $fiability_q = q$. 

Add this new metric to `openstef.metrics.metrics` 

**TEST:**  
- the models without quantiles should keep the old behavior
- the quantile models should compute the fiabilities in the reporter.

This issue is related to  #403 both need to retrieve the quantiles list in the reporter.

**Comment by JanMaartenvanDoorn** [comment]
Maybe also have a look at the CRPS: https://www.lokad.com/continuous-ranked-probability-score
Maybe also add a standard function for creating a QQ plot
