### ISSUE TITLE
Split components has unclear docstring and name

### ISSUE THREAD

**Issue by FrankKr** [OpenSTEF/openstef#41]
**Is your request related to a problem? Please describe.**
https://github.com/alliander-opensource/short-term-forecasting/blob/develop/openstf/tasks/split_forecast_into_components.py
1. The tast that calculates the split-coefs has an unclear name (does it calculate the coefs, or does it split the forecast in seperate time series?)
2. The docstring of the task is unclear. 

**Describe the solution you'd like**
At least update the docstring. Updating the name can possibly cause compatibility issue, but would be preferred as well for clarity

**Comment by Davidswinkels** [comment]
@FrankKr Is this issue still relevant? There are some docstrings in split_forecast.py: https://github.com/OpenSTEF/openstf/blob/main/openstf/tasks/split_forecast.py
