### ISSUE TITLE
Error starting OpenSTEF Reference docker container

### ISSUE THREAD

**Issue by bjth-dev** [OpenSTEF/openstef#420]
I’m trying to start the OpenSTEF Reference docker, but get the error shown in attached picture.
![error](https://user-images.githubusercontent.com/60001535/204225828-03487989-5681-4983-a540-3df1b4895f78.png)
Could you please help me with this?

**Comment by FrankKr** [comment]
@bjth-dev Whoops, it appears we have missed this issue. Sorry and thanks for sharing your error!
The OpenSTEF Reference has received a major update recently, so I am hopeful that it has fixed the issue you encountered as well. 
I am closing this issue for now, but I would be very thankful if you could let us know if the issue persists!
