### ISSUE TITLE
Logo on https://openstef.github.io/ does not load

### ISSUE THREAD

**Issue by Jonasvdbo** [OpenSTEF/openstef#439]
Hi,

I noticed that the logo on https://openstef.github.io/openstef/index.html doesn't load.

See screenshot:

![image](https://user-images.githubusercontent.com/3628277/217226933-ec2862f8-f68a-4cf7-a5fe-c735429d6f90.png)

Best regards,
Jonas

**Comment by FrankKr** [comment]
fixed
