### ISSUE TITLE
Make flow chart of data validation and feature engineering modules

### ISSUE THREAD

**Issue by bremme** [OpenSTEF/openstef#8]
WHAT: Now the data validation and feature engineering modules are a bit fuzzy. Make a flow chart to map how the functions in these modules connect and which data in what format are passed throug.

HOW:
- Have a look in the repository
- Make a drawing of how the functions connect
- Publish on wiki

TEST:
- Clear overview of structure of data validation and feature engineering modules on wiki

**Comment by FrankKr** [comment]
Is this now tackled by https://github.com/alliander-opensource/short-term-forecasting/tree/feature-KTPS-127-reorganize-modules-and-packages ? -> Parhaps still add the figure from that PR somewhere logical
